### ISSUE TITLE
CSI Chart should use Digests in it's image reference

### ISSUE THREAD

**Issue by slauger** [IBM/ibm-spectrum-scale-container-native-helm#1]
Currently all images in the `ibm-spectrum-scale` chart and operator are referenced with a Digest, e.g.

```
# Scale-Core-Operator
operator:
  image:
    name: "icr.io/cpopen/ibm-spectrum-scale-operator@sha256:fe9d63c2b7733a5f8d7e1bc80e18de0160e298db14342c77aa4c6d2e26c4ee20"
    pullPolicy: Always
```

However this is not the case for the `ibm-spectrum-scale-csi` chart.

```
csiOperator:
  image:
    # Scale CSI Operator image name (including full image registry path) and tag, e.g. "quay.io/ibm-spectrum-scale/ibm-spectrum-scale-csi-operator:v2.2.0"
    # If tag is set to "" it defaults to the chart appVersion defined in Chart.yaml.
    name: "quay.io/ibm-spectrum-scale/ibm-spectrum-scale-csi-operator"
    tag:  ""
```

Also the CSI chart has currently no option to override the CSI image (ENV `CSI_DRIVER_IMAGE`):

https://github.com/IBM/ibm-spectrum-scale-container-native-helm/blob/main/helm/ibm-spectrum-scale-csi/templates/csi-operator.yaml#L56

Background: we try to deploy spectrum scale in an Air-Gappend environment via the Helm Chart. To simplify the deployment proccess we tried to set a image mirror on CRI-O level with `mirror-by-digest-only=true`, but this only works for the main chart.
